language: node_js

node_js:
  - "10"

install:
  - npm install

os:
  - linux
  - windows

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: lint
      script:
        - node --version
        - npm --version
        - echo "Linting Started ..."
        - npm run tslint
        - echo "Linting Finished."

    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."

    - stage: publish
      before_deploy:
        - echo "Publishing npm package ..."
      after_deploy:
        - echo "Publish npm package successfully!"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
