language: node_js

node_js:
  - "10"

install:
  - npm install

os:
  - linux
  - windows

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: lint
      script:
        - node --version
        - npm --version
        - echo "Linting Started ..."
        - npm run tslint
        - echo "Linting Finished."

    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."

    - stage: publish
      script:
        - echo "Publishing npm package ..."
        - npm version
        - npm publish
        - echo "Publish npm package successfully!"

      publish:
        provider: script
        script: "cp .npmrc.template $HOME/.npmrc && npm publish"
        skip_cleanup: true
        on:
          tags: true
